# -*- generated by 1.0.9 -*-
import da
PatternExpr_234 = da.pat.TuplePattern([da.pat.ConstantPattern('ack'), da.pat.FreePattern('c2'), da.pat.BoundPattern('_BoundPattern238_')])
PatternExpr_278 = da.pat.TuplePattern([da.pat.ConstantPattern('request'), da.pat.FreePattern('c2'), da.pat.FreePattern('p')])
PatternExpr_304 = da.pat.TuplePattern([da.pat.ConstantPattern('release'), da.pat.FreePattern(None), da.pat.FreePattern('p')])
PatternExpr_363 = da.pat.TuplePattern([da.pat.ConstantPattern('done')])
PatternExpr_368 = da.pat.BoundPattern('_BoundPattern370_')
PatternExpr_371 = da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.FreePattern(None), da.pat.BoundPattern('_BoundPattern377_')]), da.pat.TuplePattern([da.pat.ConstantPattern('done')])])
PatternExpr_453 = da.pat.TuplePattern([da.pat.ConstantPattern('done'), da.pat.BoundPattern('_BoundPattern456_')])
PatternExpr_459 = da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.FreePattern(None), da.pat.FreePattern(None)]), da.pat.TuplePattern([da.pat.ConstantPattern('done'), da.pat.BoundPattern('_BoundPattern469_')])])
_config_object = {'channel': 'fifo', 'clock': 'lamport'}
import sys

class P(da.DistProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._PReceivedEvent_0 = []
        self._PReceivedEvent_3 = []
        self._events.extend([da.pat.EventPattern(da.pat.ReceivedEvent, '_PReceivedEvent_0', PatternExpr_234, sources=None, destinations=None, timestamps=None, record_history=True, handlers=[]), da.pat.EventPattern(da.pat.ReceivedEvent, '_PReceivedEvent_1', PatternExpr_278, sources=None, destinations=None, timestamps=None, record_history=None, handlers=[self._P_handler_277]), da.pat.EventPattern(da.pat.ReceivedEvent, '_PReceivedEvent_2', PatternExpr_304, sources=None, destinations=None, timestamps=None, record_history=None, handlers=[self._P_handler_303]), da.pat.EventPattern(da.pat.ReceivedEvent, '_PReceivedEvent_3', PatternExpr_363, sources=[PatternExpr_368], destinations=None, timestamps=None, record_history=True, handlers=[])])

    def setup(self, s, nrequests, **rest_475):
        super().setup(s=s, nrequests=nrequests, **rest_475)
        self._state.s = s
        self._state.nrequests = nrequests
        self._state.q = set()

    def run(self):

        def task():
            self.output('in cs')
        for i in range(self._state.nrequests):
            self.mutex(task)
        self.send(('done', self._id), to=self.parent())
        super()._label('_st_label_360', block=False)
        _st_label_360 = 0
        while (_st_label_360 == 0):
            _st_label_360 += 1
            if PatternExpr_371.match_iter(self._PReceivedEvent_3, _BoundPattern377_=self.parent(), SELF_ID=self._id):
                _st_label_360 += 1
            else:
                super()._label('_st_label_360', block=True)
                _st_label_360 -= 1
        self.output('terminating')

    def mutex(self, task):
        super()._label('request', block=False)
        c = self.logical_clock()
        self.send(('request', c, self._id), to=self._state.s)
        self._state.q.add(('request', c, self._id))
        super()._label('_st_label_199', block=False)
        p = c2 = None

        def UniversalOpExpr_201():
            nonlocal p, c2
            for (_ConstantPattern205_, c2, p) in self._state.q:
                if (_ConstantPattern205_ == 'request'):
                    if (not (((c2, p) == (c, self._id)) or ((c, self._id) < (c2, p)))):
                        return False
            return True
        p = c2 = None

        def UniversalOpExpr_227():
            nonlocal p, c2
            for p in self._state.s:

                def ExistentialOpExpr_232(p):
                    nonlocal c2
                    for (_, _, (_ConstantPattern249_, c2, _BoundPattern252_)) in self._PReceivedEvent_0:
                        if (_ConstantPattern249_ == 'ack'):
                            if (_BoundPattern252_ == p):
                                if (c2 > c):
                                    return True
                    return False
                if (not ExistentialOpExpr_232(p=p)):
                    return False
            return True
        _st_label_199 = 0
        while (_st_label_199 == 0):
            _st_label_199 += 1
            if (UniversalOpExpr_201() and UniversalOpExpr_227()):
                _st_label_199 += 1
            else:
                super()._label('_st_label_199', block=True)
                _st_label_199 -= 1
        super()._label('critical_section', block=False)
        task()
        super()._label('release', block=False)
        self._state.q.remove(('request', c, self._id))
        self.send(('release', self.logical_clock(), self._id), to=self._state.s)

    def _P_handler_277(self, c2, p):
        self._state.q.add(('request', c2, p))
        self.send(('ack', self.logical_clock(), self._id), to=p)
    _P_handler_277._labels = None
    _P_handler_277._notlabels = None

    def _P_handler_303(self, p):
        for x in {('request', c, p) for (_ConstantPattern320_, c, _BoundPattern323_) in self._state.q if (_ConstantPattern320_ == 'request') if (_BoundPattern323_ == p)}:
            self._state.q.remove(x)
            break
    _P_handler_303._labels = None
    _P_handler_303._notlabels = None

class Node_(da.NodeProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._Node_ReceivedEvent_0 = []
        self._events.extend([da.pat.EventPattern(da.pat.ReceivedEvent, '_Node_ReceivedEvent_0', PatternExpr_453, sources=None, destinations=None, timestamps=None, record_history=True, handlers=[])])

    def run(self):
        nprocs = (int(sys.argv[1]) if (len(sys.argv) > 1) else 10)
        nrequests = (int(sys.argv[2]) if (len(sys.argv) > 2) else 1)
        ps = self.new(P, num=nprocs)
        for p in ps:
            self._setup(p, ((ps - {p}), nrequests))
        self._start(ps)
        super()._label('_st_label_445', block=False)
        p = None

        def UniversalOpExpr_446():
            nonlocal p
            for p in ps:
                if (not PatternExpr_459.match_iter(self._Node_ReceivedEvent_0, _BoundPattern469_=p)):
                    return False
            return True
        _st_label_445 = 0
        while (_st_label_445 == 0):
            _st_label_445 += 1
            if UniversalOpExpr_446():
                _st_label_445 += 1
            else:
                super()._label('_st_label_445', block=True)
                _st_label_445 -= 1
        self.send(('done',), to=ps)
