# -*- generated by 1.0.9 -*-
import da
PatternExpr_187 = da.pat.TuplePattern([da.pat.ConstantPattern('request'), da.pat.FreePattern('c2'), da.pat.FreePattern('p')])
PatternExpr_212 = da.pat.TuplePattern([da.pat.ConstantPattern('release'), da.pat.BoundPattern('_BoundPattern215_'), da.pat.BoundPattern('_BoundPattern216_')])
PatternExpr_245 = da.pat.TuplePattern([da.pat.ConstantPattern('ack'), da.pat.FreePattern('c2'), da.pat.BoundPattern('_BoundPattern249_')])
PatternExpr_281 = da.pat.TuplePattern([da.pat.ConstantPattern('request'), da.pat.FreePattern(None), da.pat.FreePattern('p')])
PatternExpr_329 = da.pat.TuplePattern([da.pat.ConstantPattern('done'), da.pat.BoundPattern('_BoundPattern332_')])
PatternExpr_335 = da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.FreePattern(None), da.pat.FreePattern(None)]), da.pat.TuplePattern([da.pat.ConstantPattern('done'), da.pat.BoundPattern('_BoundPattern345_')])])
PatternExpr_219 = da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.TuplePattern([da.pat.FreePattern(None), da.pat.FreePattern(None), da.pat.FreePattern(None)]), da.pat.TuplePattern([da.pat.ConstantPattern('release'), da.pat.BoundPattern('_BoundPattern229_'), da.pat.BoundPattern('_BoundPattern230_')])])
_config_object = {}
import sys

class P(da.DistProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._PReceivedEvent_0 = []
        self._PReceivedEvent_1 = []
        self._PReceivedEvent_2 = []
        self._PReceivedEvent_4 = []
        self._events.extend([da.pat.EventPattern(da.pat.ReceivedEvent, '_PReceivedEvent_0', PatternExpr_187, sources=None, destinations=None, timestamps=None, record_history=True, handlers=[]), da.pat.EventPattern(da.pat.ReceivedEvent, '_PReceivedEvent_1', PatternExpr_212, sources=None, destinations=None, timestamps=None, record_history=True, handlers=[]), da.pat.EventPattern(da.pat.ReceivedEvent, '_PReceivedEvent_2', PatternExpr_245, sources=None, destinations=None, timestamps=None, record_history=True, handlers=[]), da.pat.EventPattern(da.pat.ReceivedEvent, '_PReceivedEvent_3', PatternExpr_281, sources=None, destinations=None, timestamps=None, record_history=None, handlers=[self._P_handler_280]), da.pat.EventPattern(da.pat.ReceivedEvent, '_PReceivedEvent_4', PatternExpr_329, sources=None, destinations=None, timestamps=None, record_history=True, handlers=[])])

    def setup(self, s, nrequests, **rest_410):
        super().setup(s=s, nrequests=nrequests, **rest_410)
        self._state.s = s
        self._state.nrequests = nrequests
        pass

    def run(self):

        def task():
            self.output('in critical section')
        for i in range(self._state.nrequests):
            self.mutex(task)
        self.send(('done', self._id), to=self._state.s)
        super()._label('_st_label_320', block=False)
        p = None

        def UniversalOpExpr_321():
            nonlocal p
            for p in self._state.s:
                if (not PatternExpr_335.match_iter(self._PReceivedEvent_4, _BoundPattern345_=p, SELF_ID=self._id)):
                    return False
            return True
        _st_label_320 = 0
        while (_st_label_320 == 0):
            _st_label_320 += 1
            if UniversalOpExpr_321():
                _st_label_320 += 1
            else:
                super()._label('_st_label_320', block=True)
                _st_label_320 -= 1
        self.output('terminating')

    def mutex(self, task):
        super()._label('request', block=False)
        c = self.logical_clock()
        self.send(('request', c, self._id), to=self._state.s)
        super()._label('_st_label_183', block=False)
        c2 = p = None

        def UniversalOpExpr_185():
            nonlocal c2, p
            for (_, _, (_ConstantPattern204_, c2, p)) in self._PReceivedEvent_0:
                if (_ConstantPattern204_ == 'request'):
                    if (not (PatternExpr_219.match_iter(self._PReceivedEvent_1, _BoundPattern229_=c2, _BoundPattern230_=p, SELF_ID=self._id) or ((c, self._id) < (c2, p)))):
                        return False
            return True
        c2 = p = None

        def UniversalOpExpr_238():
            nonlocal c2, p
            for p in self._state.s:

                def ExistentialOpExpr_243(p):
                    nonlocal c2
                    for (_, _, (_ConstantPattern260_, c2, _BoundPattern263_)) in self._PReceivedEvent_2:
                        if (_ConstantPattern260_ == 'ack'):
                            if (_BoundPattern263_ == p):
                                if (c2 > c):
                                    return True
                    return False
                if (not ExistentialOpExpr_243(p=p)):
                    return False
            return True
        _st_label_183 = 0
        while (_st_label_183 == 0):
            _st_label_183 += 1
            if (UniversalOpExpr_185() and UniversalOpExpr_238()):
                _st_label_183 += 1
            else:
                super()._label('_st_label_183', block=True)
                _st_label_183 -= 1
        super()._label('critical_section', block=False)
        task()
        super()._label('release', block=False)
        self.send(('release', c, self._id), to=self._state.s)

    def _P_handler_280(self, p):
        self.send(('ack', self.logical_clock(), self._id), to=p)
    _P_handler_280._labels = None
    _P_handler_280._notlabels = None

class Node_(da.NodeProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._events.extend([])
    _config_object = {'channel': 'Fifo', 'clock': 'Lamport'}

    def run(self):
        nprocs = (int(sys.argv[1]) if (len(sys.argv) > 1) else 10)
        nrequests = (int(sys.argv[2]) if (len(sys.argv) > 2) else 1)
        ps = self.new(P, num=nprocs)
        for p in ps:
            self._setup(p, ((ps - {p}), nrequests))
        self._start(ps)
